apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-scheduler-config
  namespace: placeholder
data:
  "config.yaml": |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: demo-scheduler
        plugins:
          filter:
            disabled:
              - name: '*'
            enabled:
              - name: NodeUnschedulable
              - name: NodeName
              - name: TaintToleration
              - name: NodeAffinity
              - name: NodePorts
              - name: Demo
              - name: NodeResourcesFit
              - name: VolumeRestrictions
              - name: EBSLimits
              - name: GCEPDLimits
              - name: NodeVolumeLimits
              - name: AzureDiskLimits
              - name: VolumeBinding
              - name: VolumeZone
              - name: PodTopologySpread
              - name: InterPodAffinity
